<a href="new" class="button success expanded">
    Add new operator</a>

<table>
    <thead>
    <tr>
        <th>First and last name</th>
        <th>Email</th>
        <th>Role</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($data as $d):?>
        <tr>
            <td><?=$d->firstName?> <?=$d->lastName?></td>
            <td><?=$d->email?></td>
            <td><?=$d->role?></td>
            <td>
                <a href="update?id=<?=$d->password?>">Update</a>
            </td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>