<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle="example-menu"></button>
    <div class="title-bar-title">Navigation</div>
</div>

<div class="top-bar" id="example-menu">
    <div class="top-bar-left">
        <ul class="menu">

                <li><a href="#">Home</a></li>

                <li><a href="#">About</a></li>
            <?php if(!App::auth()): ?>
                <li><a href="/index/login">Login</a></li>
            <?php else: ?>
                <li><a href="/index/logout">Logout</a></li>
            <?php endif; ?>

        </ul>
    </div>

</div>